version: "2"
containers:
- name: guac
  image: gcr.io/instruqt/guacamole
  shell: /bin/bash
  ports:
  - 8080
  memory: 512
virtualmachines:
- name: nixagent1
  image: kmo-instruqt/nixagent1-pe101-lab-3-1
  shell: /bin/bash
  machine_type: n1-standard-4
- name: winagent
  image: kmo-instruqt/winagent-pe101-lab-3-1
  machine_type: n1-standard-4
- name: nixagent2
  image: kmo-instruqt/nixagent2-pe101-lab-3-1
  shell: /bin/bash
  machine_type: n1-standard-4
- name: puppet
  image: kmo-instruqt/puppet-pe101-lab-3-1
  shell: /bin/bash
  machine_type: n1-highcpu-16
