version: "3"
containers:
- name: guac
  image: gcr.io/instruqt/guacamole
  shell: /bin/bash
  ports:
  - 8080
  memory: 1024
virtualmachines:
- name: winagent
  image: kmo-instruqt/winagent-pe201-lab-2-1
  machine_type: n1-standard-4
- name: nixagent2
  image: kmo-instruqt/nixagent2-pe201-lab-2-1
  shell: /bin/bash
  machine_type: n1-standard-4
- name: nixagent1
  image: kmo-instruqt/nixagent1-pe201-lab-2-1
  shell: /bin/bash
  machine_type: n1-standard-4
- name: puppet
  image: kmo-instruqt/puppet-pe201-lab-2-1
  shell: /bin/bash
  machine_type: n1-highcpu-16
- name: gitea
  image: kmo-instruqt/gitea-pe201-lab-2-1
  shell: /bin/bash
  machine_type: n1-standard-4
