version: "2"
containers:
- name: guac
  image: gcr.io/instruqt/guacamole
  shell: /bin/bash
  ports:
  - 8080
  memory: 512
virtualmachines:
- name: nixagent
  image: kmo-instruqt/nixagent1-pe101-lab-2-0
  shell: /bin/bash
  machine_type: n1-standard-4
- name: winagent
  image: kmo-instruqt/winagent-pe101-lab-2-0
  machine_type: n1-standard-4
- name: puppet
  image: kmo-instruqt/puppet-pe101-lab-2-0
  shell: /bin/bash
  machine_type: n1-highcpu-16
