version: "2"
virtualmachines:
- name: puppet
  image: centos-7-v20201014
  shell: /bin/bash
  machine_type: n1-standard-4
- name: target1
  image: centos-7-v20201014
  shell: /bin/bash
  machine_type: n1-standard-1
- name: target2
  image: centos-7-v20201014
  shell: /bin/bash
  machine_type: n1-standard-1
